spring.application.name=nextplay

spring.datasource.url=jdbc:postgresql://localhost:5432/nextplay
spring.datasource.username=postgres
spring.datasource.password=Mada@85009

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true